tiagovaz/saskatoon

saskatoon/harvest/forms.py, saskatoon/harvest/views.py, saskatoon/saskatoon/urls.py
I've resolved the problem of autocomplete.
Some bad request in view was origins of the problems.
I've add autocomplete on address
=> fix #41 autocomplete

saskatoon/harvest/templates/harvest/equipment/list.html, saskatoon/harvest/urls.py, saskatoon/harvest/views.py, saskatoon/saskatoon/templates/base.html
fixed #39 
I've just add a ListView and a link on the main menu.
Owner and Property are in condition to a better display in the table of the list.
=> fix #39 list equipment

saskatoon/harvest/models.py, saskatoon/harvest/templates/harvest/harvest/create.html, saskatoon/harvest/views.py
With this PR we can now add harvest in the front page (and without the admin panel).
The form is the same.
=> add autocomplete on harvest create view

saskatoon/harvest/models.py, saskatoon/harvest/templates/harvest/properties/create.html, saskatoon/harvest/views.py
With this PR we can now add property in the front page (and without the admin panel).
The form is the same.
=> add autocomplete on property create view

saskatoon/harvest/templates/harvest/harvest/list.html, saskatoon/harvest/templates/harvest/properties/detail.html, saskatoon/harvest/urls.py, saskatoon/harvest/views.py
Fix #46 
I've change the label `edit` to `edit the property` in property detail
=> Fix 46 harvest for property

saskatoon/harvest/templates/harvest/harvest/update.html, saskatoon/harvest/views.py
With this PR, update is now possible with autocompletion.
=> change attr fields to form_class

saskatoon/harvest/forms.py, saskatoon/harvest/models.py, saskatoon/harvest/views.py
RequestForParticipation c'est pas le fun.
=> Rfp refactoring

saskatoon/harvest/models.py, saskatoon/harvest/templates/harvest/equipment/create.html, saskatoon/harvest/templates/harvest/properties/detail.html, saskatoon/harvest/urls.py, saskatoon/harvest/views.py
=> add equipment from property detail

saskatoon/harvest/templates/harvest/harvest/list.html
Fix #62
Add link to property from harvest list
=> add link to property from harvest

saskatoon/harvest/forms.py
Fix #103 
Add format for widget and input in forms.py
=> set input format and widget format in forms.py

saskatoon/pages/views.py
fixed #100 
Just allow staff to see all harvest without check if they are publisheable
=> allow staff to see all harvests

saskatoon/harvest/templates/harvest/harvest/list.html, saskatoon/harvest/templates/harvest/properties/list.html
=> fix order in list

.gitignore, INSTALL.md, requirements.txt, saskatoon/harvest/admin.py, saskatoon/harvest/filters.py, saskatoon/harvest/forms.py, saskatoon/harvest/models.py, saskatoon/harvest/templates/harvest/harvest/list.html, saskatoon/harvest/views.py, saskatoon/member/models.py, saskatoon/saskatoon/context_processor.py
Some improvment to change supported python version
- Update requirements
- Refactor print to the function print in py3
- Fix some bad import in top of files
- Fix some raise to the new function raise in py3
- Update install process
- Refactor HarvestFilter to integrate the external function in the class and fix the load error in django migrate command
=> Update to python3

saskatoon/harvest/translation.py, saskatoon/saskatoon/static/sbadmin2/dist/js/sb-admin-2.js, saskatoon/saskatoon/templates/base.html
Issue : #119 
Add a new footer who contain the name of the system, the version and the license.
Hardcode height of the footer in the JS who refresh the full-height of the page in sbadmin2
=> Add footer

saskatoon/harvest/templates/harvest/organizations/add_image.html, saskatoon/harvest/templates/harvest/organizations/create.html, saskatoon/harvest/templates/harvest/organizations/detail.html, saskatoon/harvest/templates/harvest/organizations/list.html, saskatoon/harvest/templates/harvest/organizations/update.html, saskatoon/harvest/urls.py, saskatoon/harvest/views.py, saskatoon/member/models.py, saskatoon/saskatoon/templates/base.html
=> Add view for organizations list.

saskatoon/harvest/filters.py
=> Fix season filter.

saskatoon/member/admin.py
=> Fix change-pass form in admin.

saskatoon/saskatoon/templates/base.html
=> Improving admin menu.

saskatoon/harvest/views.py
=> Show only beneficiaries.

saskatoon/harvest/templates/harvest/organizations/list.html
=> Show only beneficiaries - fix template..

saskatoon/member/models.py
=> Return email when there is no name set.

saskatoon/pages/templates/pages/dashboard.html, saskatoon/pages/urls.py
=> Add landing page before going to the calendar.

saskatoon/harvest/models.py
=> No requests when Ready.

saskatoon/harvest/templates/harvest/stats/stats.html, saskatoon/harvest/views.py
=> More stats

saskatoon/harvest/templates/harvest/stats/stats.html, saskatoon/harvest/urls.py, saskatoon/harvest/views.py
=> Improve stats

saskatoon/harvest/templates/harvest/stats/stats.html, saskatoon/harvest/urls.py, saskatoon/harvest/views.py
=> Picker stats

saskatoon/harvest/templates/harvest/stats/stats.html, saskatoon/harvest/views.py, saskatoon/saskatoon/templates/base.html
=> First stats stable.

saskatoon/harvest/templates/harvest/stats/stats.html
=> Default 0 if None.

saskatoon/saskatoon/templates/base.html
=> Formating content block.
